SET @TIME = -1;

SELECT @TIME := @TIME + 1 AS HOUR,
    (
        SELECT COUNT(DATETIME)
        FROM ANIMAL_OUTS
        WHERE @TIME = HOUR(DATETIME)
    ) AS COUNT
FROM ANIMAL_OUTS
WHERE @TIME < 23
ORDER BY @TIME;
